<a href="https://colab.research.google.com/github/SnehaChauhan1174/meeting-summarizer/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print("GPU",torch.cuda.is_available())
print("GPU name:",torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

GPU True
GPU name: Tesla T4

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

ValueError: Mountpoint must not already contain files

In [ ]:
import os
base = "/content/drive/MyDrive/meeting_summarizer"

folders = [
    "data/audio",
    "data/transcripts",
    "data/test_meetings",
    "outputs",
    "scripts"
]

for f in folders:
  os.makedirs(f"{base}/{f}",exist_ok=True)

print("folders created at:",base)

folders created at: /content/drive/MyDrive/meeting_summarizer

In [ ]:
print("RAM:", torch.cuda.get_device_properties(0).total_memory / 1e9, "GB")

RAM: 15.637086208 GB

In [ ]:
%%bash
pip install -q datasets huggingface_hub
echo "✅ Done"

✅ Done

In [ ]:
from datasets import load_dataset
print("loading ami dataset (text only no audio)")
ami = load_dataset("edinburghcstr/ami","ihm")

loading ami dataset (text only no audio)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/42 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/42 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/42 [00:00<?, ?files/s]

ihm/train-00000-of-00042.parquet:   0%|          | 0.00/296M [00:00<?, ?B/s]

ihm/train-00001-of-00042.parquet:   0%|          | 0.00/289M [00:00<?, ?B/s]

ihm/train-00002-of-00042.parquet:   0%|          | 0.00/270M [00:00<?, ?B/s]

ihm/train-00003-of-00042.parquet:   0%|          | 0.00/245M [00:00<?, ?B/s]

ihm/train-00004-of-00042.parquet:   0%|          | 0.00/202M [00:00<?, ?B/s]

ihm/train-00005-of-00042.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

ihm/train-00006-of-00042.parquet:   0%|          | 0.00/255M [00:00<?, ?B/s]

ihm/train-00007-of-00042.parquet:   0%|          | 0.00/276M [00:00<?, ?B/s]

ihm/train-00008-of-00042.parquet:   0%|          | 0.00/298M [00:00<?, ?B/s]

ihm/train-00009-of-00042.parquet:   0%|          | 0.00/290M [00:00<?, ?B/s]

ihm/train-00010-of-00042.parquet:   0%|          | 0.00/261M [00:00<?, ?B/s]

ihm/train-00011-of-00042.parquet:   0%|          | 0.00/279M [00:00<?, ?B/s]

ihm/train-00012-of-00042.parquet:   0%|          | 0.00/279M [00:00<?, ?B/s]

ihm/train-00013-of-00042.parquet:   0%|          | 0.00/264M [00:00<?, ?B/s]

ihm/train-00014-of-00042.parquet:   0%|          | 0.00/316M [00:00<?, ?B/s]

ihm/train-00015-of-00042.parquet:   0%|          | 0.00/281M [00:00<?, ?B/s]

ihm/train-00016-of-00042.parquet:   0%|          | 0.00/258M [00:00<?, ?B/s]

ihm/train-00017-of-00042.parquet:   0%|          | 0.00/226M [00:00<?, ?B/s]

ihm/train-00018-of-00042.parquet:   0%|          | 0.00/290M [00:00<?, ?B/s]

ihm/train-00019-of-00042.parquet:   0%|          | 0.00/412M [00:00<?, ?B/s]

ihm/train-00020-of-00042.parquet:   0%|          | 0.00/387M [00:00<?, ?B/s]

ihm/train-00021-of-00042.parquet:   0%|          | 0.00/406M [00:00<?, ?B/s]

ihm/train-00022-of-00042.parquet:   0%|          | 0.00/377M [00:00<?, ?B/s]

ihm/train-00023-of-00042.parquet:   0%|          | 0.00/367M [00:00<?, ?B/s]

ihm/train-00024-of-00042.parquet:   0%|          | 0.00/372M [00:00<?, ?B/s]

ihm/train-00025-of-00042.parquet:   0%|          | 0.00/408M [00:00<?, ?B/s]

ihm/train-00026-of-00042.parquet:   0%|          | 0.00/351M [00:00<?, ?B/s]

ihm/train-00027-of-00042.parquet:   0%|          | 0.00/395M [00:00<?, ?B/s]

ihm/train-00028-of-00042.parquet:   0%|          | 0.00/403M [00:00<?, ?B/s]

ihm/train-00029-of-00042.parquet:   0%|          | 0.00/351M [00:00<?, ?B/s]

ihm/train-00030-of-00042.parquet:   0%|          | 0.00/380M [00:00<?, ?B/s]

ihm/train-00031-of-00042.parquet:   0%|          | 0.00/233M [00:00<?, ?B/s]

ihm/train-00032-of-00042.parquet:   0%|          | 0.00/216M [00:00<?, ?B/s]

ihm/train-00033-of-00042.parquet:   0%|          | 0.00/217M [00:00<?, ?B/s]

ihm/train-00034-of-00042.parquet:   0%|          | 0.00/285M [00:00<?, ?B/s]

ihm/train-00035-of-00042.parquet:   0%|          | 0.00/237M [00:00<?, ?B/s]

ihm/train-00036-of-00042.parquet:   0%|          | 0.00/263M [00:00<?, ?B/s]

ihm/train-00037-of-00042.parquet:   0%|          | 0.00/248M [00:00<?, ?B/s]

ihm/train-00038-of-00042.parquet:   0%|          | 0.00/232M [00:00<?, ?B/s]

ihm/train-00039-of-00042.parquet:   0%|          | 0.00/247M [00:00<?, ?B/s]

ihm/train-00040-of-00042.parquet:   0%|          | 0.00/244M [00:00<?, ?B/s]

ihm/train-00041-of-00042.parquet:   0%|          | 0.00/205M [00:00<?, ?B/s]

ihm/validation-00000-of-00005.parquet:   0%|          | 0.00/339M [00:00<?, ?B/s]

ihm/validation-00001-of-00005.parquet:   0%|          | 0.00/354M [00:00<?, ?B/s]

ihm/validation-00002-of-00005.parquet:   0%|          | 0.00/236M [00:00<?, ?B/s]

ihm/validation-00003-of-00005.parquet:   0%|          | 0.00/407M [00:00<?, ?B/s]

ihm/validation-00004-of-00005.parquet:   0%|          | 0.00/244M [00:00<?, ?B/s]

ihm/test-00000-of-00004.parquet:   0%|          | 0.00/242M [00:00<?, ?B/s]

ihm/test-00001-of-00004.parquet:   0%|          | 0.00/292M [00:00<?, ?B/s]

ihm/test-00002-of-00004.parquet:   0%|          | 0.00/426M [00:00<?, ?B/s]

ihm/test-00003-of-00004.parquet:   0%|          | 0.00/332M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/108502 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13098 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/12643 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/36 [00:00<?, ?it/s]

In [ ]:
ami["train"].features

{'meeting_id': Value('string'),
 'audio_id': Value('string'),
 'text': Value('string'),
 'audio': Audio(sampling_rate=16000, decode=True, stream_index=None),
 'begin_time': Value('float32'),
 'end_time': Value('float32'),
 'microphone_id': Value('string'),
 'speaker_id': Value('string')}

configuring github

In [ ]:
# to load only specific columns to save memory

from datasets import load_dataset, Features, Value

features = Features({
    "meeting_id": Value("string"),
    "text": Value("string")
})

ami = load_dataset("edinburghcstr/ami", "ihm", features=features)

In [ ]:
# sec option is to remove after loading
ami = ami.remove_columns(["audio_id", "audio"])

In [ ]:
print(ami)

DatasetDict({
    train: Dataset({
        features: ['meeting_id', 'text', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'],
        num_rows: 108502
    })
    validation: Dataset({
        features: ['meeting_id', 'text', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'],
        num_rows: 13098
    })
    test: Dataset({
        features: ['meeting_id', 'text', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'],
        num_rows: 12643
    })
})

In [ ]:
sample = ami['train'][0]
print(sample.keys())

dict_keys(['meeting_id', 'text', 'begin_time', 'end_time', 'microphone_id', 'speaker_id'])

In [ ]:
type(sample)

dict

In [ ]:
print(sample)

{'meeting_id': 'EN2001a', 'audio_id': 'AMI_EN2001a_H04_MEO069_0330297_0330718', 'text': 'IF YOU IF YOU S. S. H. AND THEY HAVE THIS BIG WARNING ABOUT DOING NOTHING AT ALL IN THE GATEWAY MACHINE', 'audio': <datasets.features._torchcodec.AudioDecoder object at 0x7f5cc2996030>, 'begin_time': 3302.969970703125, 'end_time': 3307.179931640625, 'microphone_id': 'H04', 'speaker_id': 'MEO069'}

In [ ]:
from datasets import config
print(config.HF_DATASETS_CACHE)

/root/.cache/huggingface/datasets

In [ ]:
type(ami)

datasets.dataset_dict.DatasetDict

for data preprocessing we need to convert dict dataset to dataframe so .to_pandas()

In [ ]:
train_df = ami["train"].to_pandas()
train_df.head(5)

,meeting_id,text,begin_time,end_time,microphone_id,speaker_id
0,EN2001a,IF YOU IF YOU S. S. H. AND THEY HAVE THIS BIG ...,3302.969971,3307.179932,H04,MEO069
1,EN2001a,I'VE GOTTEN MM HARDLY ANY,4149.149902,4150.779785,H00,MEE068
2,EN2001a,IT'S YEAH I MEAN THE WAVE DATA ARE OBVIOUSLY N...,3192.899902,3198.149902,H03,MEE067
3,EN2001a,YEAH IT'LL IT'LL PLAY THEM IN SOME ORDER IN WH...,1455.150024,1461.520020,H04,MEO069
4,EN2001a,YEAH,4781.270020,4781.640137,H03,MEE067

In [ ]:
test_df = ami["test"].to_pandas()
test_df.head(5)

,meeting_id,text,begin_time,end_time,microphone_id,speaker_id
0,EN2002a,YEAH,196.630005,198.000000,H00,MEE073
1,EN2002a,MM-HMM,1223.079956,1223.449951,H02,FEO072
2,EN2002a,YEAH WE'RE GONNA MEET UP,1214.160034,1215.339966,H01,FEO070
3,EN2002a,I MEAN WE'RE NOT EVEN THERE YET,357.130005,358.489990,H02,FEO072
4,EN2002a,YEAH,872.780029,873.070007,H01,FEO070

In [ ]:
val_df = ami["validation"].to_pandas()
val_df.head(5)

,meeting_id,text,begin_time,end_time,microphone_id,speaker_id
0,ES2011a,BUT LIKE MOBILE PHONES HAVE SCREENS AND THEY'R...,927.840027,930.520020,H03,FEE044
1,ES2011a,MM,928.140015,928.289978,H00,FEE041
2,ES2011a,FURRY,960.979980,961.500000,H02,FEE043
3,ES2011a,YEAH,174.839996,176.699997,H00,FEE041
4,ES2011a,I MEAN IT JUST SEEMS LIKE YEAH,845.570007,847.840027,H02,FEE043

In [ ]:
print("Train shape:", train_df.shape)
print("Val shape:  ", val_df.shape)
print("Test shape: ", test_df.shape)

Train shape: (108502, 6)
Val shape:   (13098, 6)
Test shape:  (12643, 6)

In [ ]:
# cleaning testing on 10% of data
train_sample = train_df.sample(frac=0.1, random_state=42).copy()

In [ ]:
train_sample

,meeting_id,text,begin_time,end_time,microphone_id,speaker_id
72375,IS1004d,YEAH,338.119995,339.329987,H01,MIE090
87376,TS3006d,NO N I I ALREADY DID IT,14.670000,17.299999,H01,MTD023UID
66539,IS1002b,RIGHT AS FAR AS I IT'S JUST UH THE COST OF AN ...,724.609985,728.130005,H01,MIE029
18086,ES2002c,OKAY,581.109985,581.520020,H01,FEE005
49687,IN1001,HMM,2819.139893,2819.379883,H02,MIO066
...,...,...,...,...,...,...
34646,ES2010b,IS THAT GONNA PUSH US OVER OUR PRODUCTION COSTS,752.460022,754.609985,H02,FEE039
72327,IS1004d,YEAH SO LET'S PUT ONE HERE IN THE THEN INSTEAD...,1463.670044,1469.069946,H00,MIO019
65949,IS1002b,AND SO WE HAVE TO GO I THINK IN THE OTHER DIRE...,183.919998,186.289993,H03,MIE083
91908,TS3008a,UH,1032.630005,1032.920044,H00,MTD029PM
68829,IS1003c,OH N YEAH YEAH THA THAT'S WHY WE HAVE TO DO LA...,499.149994,502.470001,H02,MIO035

In [ ]:
print(train_sample.shape)
print(train_sample.dtypes)
print(train_sample.isnull().sum())          # Missing values
print(train_sample.duplicated().sum())      # Duplicates
print(train_sample.describe())              # Stats for numerical attributes

(10850, 6)
meeting_id        object
text              object
begin_time       float32
end_time         float32
microphone_id     object
speaker_id        object
dtype: object
meeting_id       0
text             0
begin_time       0
end_time         0
microphone_id    0
speaker_id       0
dtype: int64
0
         begin_time      end_time
count  10850.000000  10850.000000
mean    1302.364014   1304.937866
std      883.045044    882.938904
min        0.020000      1.860000
25%      621.467514    625.832520
50%     1185.864990   1187.464966
75%     1821.957489   1823.357483
max     5289.220215   5292.430176

In [ ]:
# Check missing values
print(train_df.isnull().sum())

# Check for empty/blank text
print("Empty text rows:", (train_df["text"].str.strip() == "").sum())

# Check duplicates
print("Duplicate rows:", train_df.duplicated().sum())

meeting_id       0
text             0
begin_time       0
end_time         0
microphone_id    0
speaker_id       0
dtype: int64
Empty text rows: 0
Duplicate rows: 0

In [ ]:
# handling all empty text
print(len(train_sample))

empty_mask = train_sample['text'].str.strip() == ''
print(f"\nEmpty/whitespace rows:{empty_mask.sum()}")
print("empty rows:")
print(train_sample[empty_mask][['meeting_id','speaker_id','text']].head())

10850

Empty/whitespace rows:0
empty rows:
Empty DataFrame
Columns: [meeting_id, speaker_id, text]
Index: []

In [ ]:
# lowercasing the text
print("sample before lowercase")
print(train_sample["text"].head(5).tolist())

train_sample2 = train_sample.copy()
train_sample2["text"] = train_sample2["text"].str.lower()

print("sample after lowercase")
print(train_sample2["text"].head(5).tolist())

sample before lowercase
['YEAH', 'NO N I I ALREADY DID IT', "RIGHT AS FAR AS I IT'S JUST UH THE COST OF AN EXTRA BUTTON", 'OKAY', 'HMM']
sample after lowercase
['yeah', 'no n i i already did it', "right as far as i it's just uh the cost of an extra button", 'okay', 'hmm']

In [26]:
# dropping single words utterances
backchannels = {
    'yeah','yep','yup','yes','no','nope','okay','ok','right',
    'sure','fine','hmm','mm','mhm','uh','oh','ohh','ahh','ah',
    'good','great','cool','nice','thanks','thank','alright','exactly'
}

def is_pure_backchannel(text):
  words = set(str(text).strip().split())
  return words.issubset(backchannels)

backchannel_mask = train_sample2["text"].apply(is_pure_backchannel)
print(f"pure backchannel rows:{backchannel_mask.sum()}")
print("backchannel rows being dropped:")
print(train_sample2[backchannel_mask]['text'].value_counts().head(10))

train_sample3 = train_sample2[~backchannel_mask].copy()

print(f"rows dropped:{len(train_sample2)-len(train_sample3)}")

pure backchannel rows:2536
backchannel rows being dropped:
text
yeah         1011
okay          464
mm            209
hmm            96
right          96
uh             68
no             61
yes            61
yeah yeah      52
oh             48
Name: count, dtype: int64
rows dropped:2536

In [27]:
train_sample3.head(10)

,meeting_id,text,begin_time,end_time,microphone_id,speaker_id
87376,TS3006d,no n i i already did it,14.670000,17.299999,H01,MTD023UID
66539,IS1002b,right as far as i it's just uh the cost of an ...,724.609985,728.130005,H01,MIE029
64695,IS1001b,uh maybe messenger ami,182.039993,183.330002,H01,MIO012
7389,EN2005a,but those are very those are really different ...,944.429993,952.429993,H03,FEE085
102461,TS3011b,do do you want a list of functions,1442.920044,1444.650024,H02,MTD042ID
101392,TS3010d,we can put it in it,538.039978,539.750000,H00,MTD037PM
53686,IN1008,basic information we need,994.929993,996.789978,H02,MIO101
5705,EN2003a,if you do two in a row then that's an hour isn...,489.730011,491.359985,H01,MEE076
73797,IS1005c,everybody's agreed,1524.760010,1525.560059,H00,MIO055
91530,TS3007d,we we want a more adult version,409.059998,410.880005,H02,MTD026UID

In [29]:
# removing filler words from text
import re
fillers = r'\b(um|uh|er|ah|hmm|mm|hm|uhh|umm|eh|mhm|huh|oh)\b'

has_fillers = train_sample3['text'].str.contains(fillers, flags=re.IGNORECASE, regex=True)
print(f"Rows containing fillers : {has_fillers.sum()}")
print(f"\nSample rows WITH fillers (before):")
print(train_sample3[has_fillers]['text'].head(5).tolist())

# apply the removal
train_sample4 = train_sample3.copy()
train_sample4['text']=train_sample4['text'].str.replace(fillers,'',regex=True,case=False)


# Fix extra spaces
train_sample4['text'] = train_sample4['text'].str.replace(r'\s+', ' ', regex=True).str.strip()

print(f"\nSame rows AFTER filler removal:")
print(train_sample4[has_fillers]['text'].head(5).tolist())

Rows containing fillers : 2704

Sample rows WITH fillers (before):
["right as far as i it's just uh the cost of an extra button", 'uh maybe messenger ami', 'but those are very those are really different um theories that are at are trying to get at different things and it and they admit of m you know', "oh okay but 'kay look", 'and you can uh then adjust it with the zapping buttons or something']

Same rows AFTER filler removal:
["right as far as i it's just the cost of an extra button", 'maybe messenger ami', 'but those are very those are really different theories that are at are trying to get at different things and it and they admit of m you know', "okay but 'kay look", 'and you can then adjust it with the zapping buttons or something']

/tmp/ipykernel_2859/1203343878.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  has_fillers = train_sample3['text'].str.contains(fillers, flags=re.IGNORECASE, regex=True)

In [30]:
FRAGMENT_PATTERN = r'\b\w+-(?=\s|$)'

# See fragments before
has_fragments = train_sample4['text'].str.contains(FRAGMENT_PATTERN, regex=True)
print(f"Rows with broken fragments : {has_fragments.sum()}")
print(f"\nSample fragments (before):")
print(train_sample4[has_fragments]['text'].head(5).tolist())

Rows with broken fragments : 0

Sample fragments (before):
[]

In [31]:
MIN_WORDS = 3

# Word count after all cleaning
train_sample4['word_count'] = train_sample4['text'].str.split().str.len()

print(f"\nWord count distribution:")
print(train_sample4['word_count'].value_counts().sort_index().head(10))

Word count distribution:
word_count
0     124
1    1018
2     691
3     650
4     562
5     524
6     445
7     460
8     382
9     371
Name: count, dtype: int64

In [32]:
train_sample4

,meeting_id,text,begin_time,end_time,microphone_id,speaker_id,word_count
87376,TS3006d,no n i i already did it,14.670000,17.299999,H01,MTD023UID,7
66539,IS1002b,right as far as i it's just the cost of an ext...,724.609985,728.130005,H01,MIE029,13
64695,IS1001b,maybe messenger ami,182.039993,183.330002,H01,MIO012,3
7389,EN2005a,but those are very those are really different ...,944.429993,952.429993,H03,FEE085,28
102461,TS3011b,do do you want a list of functions,1442.920044,1444.650024,H02,MTD042ID,8
...,...,...,...,...,...,...,...
67177,IS1002c,'kay,976.849976,977.229980,H00,MIE080,1
34646,ES2010b,is that gonna push us over our production costs,752.460022,754.609985,H02,FEE039,9
72327,IS1004d,yeah so let's put one here in the then instead...,1463.670044,1469.069946,H00,MIO019,15
65949,IS1002b,and so we have to go i think in the other dire...,183.919998,186.289993,H03,MIE083,12
68829,IS1003c,n yeah yeah tha that's why we have to do langu...,499.149994,502.470001,H02,MIO035,12

In [38]:
import re
import pandas as pd


FILLERS = r'\b(um|uh|er|ah|hmm|mm|hm|uhh|umm|eh|mhm|huh|oh)\b'

BACKCHANNELS = {
    'yeah', 'yep', 'yup', 'yes', 'no', 'nope',
    'okay', 'ok', 'right', 'sure', 'fine',
    'hmm', 'mm', 'mhm', 'uh', 'oh', 'ah',
    'good', 'great', 'cool', 'nice',
    'thanks', 'thank', 'alright'
}

FRAGMENT_PATTERN = r'\b\w+-(?=\s|$)'
MIN_WORDS        = 3

def clean_ami_dataframe(df):

    # track rows at each step
    # stats = {'raw': len(df)}

    # Drop NULL text
    df = df.dropna(subset=['text']).copy()
    # stats['after_null_drop'] = len(df)
    # print(f"\n NULL drop        : {stats['raw']} → {stats['after_null_drop']}  (-{stats['raw'] - stats['after_null_drop']} rows)")

    # Drop empty/whitespace
    mask = df['text'].str.strip() == ''
    df   = df[~mask].copy()
    # stats['after_empty_drop'] = len(df)
    # print(f"Empty drop       : {stats['after_null_drop']} → {stats['after_empty_drop']}  (-{stats['after_null_drop'] - stats['after_empty_drop']} rows)")

    # Lowercase
    df['text'] = df['text'].str.lower()
    # stats['after_lower'] = len(df)
    # print(f"Lowercase        : {stats['after_empty_drop']} → {stats['after_lower']}  (-0 rows)")

    #  Drop pure backchannels
    def is_backchannel(text):
        return set(str(text).strip().split()).issubset(BACKCHANNELS)

    mask = df['text'].apply(is_backchannel)
    df   = df[~mask].copy()
    # stats['after_backchannel'] = len(df)
    # print(f"Backchannel drop : {stats['after_lower']} → {stats['after_backchannel']}  (-{stats['after_lower'] - stats['after_backchannel']} rows)")

    # Remove filler words
    df['text'] = df['text'].str.replace(FILLERS, ' ', regex=True, case=False)
    df['text'] = df['text'].str.replace(r'\s+', ' ', regex=True).str.strip()
    # stats['after_fillers'] = len(df)
    # print(f"Filler removal   : {stats['after_backchannel']} → {stats['after_fillers']}  (-0 rows, text cleaned)")


    #Drop short utterances
    df['word_count'] = df['text'].str.split().str.len()
    mask = df['word_count'] < MIN_WORDS
    df   = df[~mask].drop(columns=['word_count']).copy()
    # stats['after_short_drop'] = len(df)
    # print(f"Short drop       : {stats['after_fragments']} → {stats['after_short_drop']}  (-{stats['after_fragments'] - stats['after_short_drop']} rows)")

    # FINAL SUMMARY

    # print(f"  TOTAL REMOVED : {stats['raw'] - stats['after_short_drop']} rows")
    # print(f"  DATA RETAINED : {stats['after_short_drop'] / stats['raw'] * 100:.1f}%")


    return df

In [39]:
df_clean_sample = clean_ami_dataframe(train_sample)

print(df_clean_sample[['meeting_id', 'speaker_id', 'text', 'begin_time']].head(10))

       meeting_id speaker_id  \
87376     TS3006d  MTD023UID
66539     IS1002b     MIE029
64695     IS1001b     MIO012
7389      EN2005a     FEE085
102461    TS3011b   MTD042ID
101392    TS3010d   MTD037PM
53686      IN1008     MIO101
5705      EN2003a     MEE076
91530     TS3007d  MTD026UID
101411    TS3010d   MTD037PM

                                                     text   begin_time
87376                             no n i i already did it    14.670000
66539   right as far as i it's just the cost of an ext...   724.609985
64695                                 maybe messenger ami   182.039993
7389    but those are very those are really different ...   944.429993
102461                 do do you want a list of functions  1442.920044
101392                                we can put it in it   538.039978
53686                           basic information we need   994.929993
5705    if you do two in a row then that's an hour isn...   489.730011
91530                     we we want a more adult version   409.059998
101411             so we have to change that a little bit  1392.550049

In [44]:
# applying cleaning function to all 3 splits
df_train_clean = clean_ami_dataframe(train_df)
df_val_clean   = clean_ami_dataframe(val_df)
df_test_clean  = clean_ami_dataframe(test_df)

In [41]:
df_train_clean

,meeting_id,text,begin_time,end_time,microphone_id,speaker_id
0,EN2001a,if you if you s. s. h. and they have this big ...,3302.969971,3307.179932,H04,MEO069
1,EN2001a,i've gotten hardly any,4149.149902,4150.779785,H00,MEE068
2,EN2001a,it's yeah i mean the wave data are obviously n...,3192.899902,3198.149902,H03,MEE067
3,EN2001a,yeah it'll it'll play them in some order in wh...,1455.150024,1461.520020,H04,MEO069
6,EN2001a,all these fancy pens,1719.410034,1720.869995,H04,MEO069
...,...,...,...,...,...,...
108494,TS3012d,okay let's eval evaluate the product of us our...,839.539978,847.900024,H03,MTD048ME
108495,TS3012d,yeah if we make it into a four as in neutral b...,1320.430054,1324.989990,H01,MTD047UID
108497,TS3012d,we could have used it more efficiently we just...,1355.150024,1357.689941,H00,MTD045PM
108498,TS3012d,special colour yeah,331.220001,332.079987,H03,MTD048ME
108499,TS3012d,one two three,1260.160034,1262.500000,H00,MTD045PM

In [42]:
df_val_clean

,meeting_id,text,begin_time,end_time,microphone_id,speaker_id
0,ES2011a,but like mobile phones have screens and they'r...,927.840027,930.520020,H03,FEE044
4,ES2011a,i mean it just seems like yeah,845.570007,847.840027,H02,FEE043
7,ES2011a,so you should have a call button on your telev...,672.119995,676.090027,H02,FEE043
10,ES2011a,but it's something to think about yeah,940.659973,942.979980,H00,FEE041
13,ES2011a,if we'll all draw our favourite animal to sum ...,157.029999,164.100006,H00,FEE041
...,...,...,...,...,...,...
13090,TS3004d,in the bottom,881.340027,881.929993,H02,MTD014ID
13091,TS3004d,well w we thought of a text button,700.239990,702.739990,H02,MTD014ID
13093,TS3004d,and you turn it off then the next time you tur...,727.609985,732.630005,H03,MTD016ME
13094,TS3004d,i think we discussed a lot of things about it,1716.680054,1718.989990,H01,MTD015UID
13095,TS3004d,most new t. v. s do collect all the pages,765.200012,770.059998,H03,MTD016ME

In [43]:
df_test_clean

,meeting_id,text,begin_time,end_time,microphone_id,speaker_id
2,EN2002a,yeah we're gonna meet up,1214.160034,1215.339966,H01,FEO070
3,EN2002a,i mean we're not even there yet,357.130005,358.489990,H02,FEO072
7,EN2002a,get to use my pen,287.890015,288.850006,H03,MEE071
10,EN2002a,yeah that's what we need yeah,854.700012,856.530029,H03,MEE071
11,EN2002a,three's good though,1895.920044,1896.780029,H03,MEE071
...,...,...,...,...,...,...
12630,TS3003d,for old people i i,1729.709961,1731.130005,H01,MTD011UID
12634,TS3003d,we all go for six,1694.520020,1696.349976,H03,MTD012ME
12636,TS3003d,if you push it three times,1049.859985,1051.810059,H00,MTD009PM
12639,TS3003d,four or five between,1732.790039,1734.310059,H00,MTD009PM
12641,TS3003d,yeah maybe when we n just give the numbers of of,2228.300049,2238.989990,H01,MTD011UID